A (Mono)Delay : VST Plug-in Test: VSTParamHasMinMax< TDATA > Class Template Reference
VSTParamHasMinMax< TDATA > Class Template Reference
#include <vst_param.h>
Public Member Functions
VSTParamHasMinMax (TDATA min=0.0, TDATA max=1.0)
VSTParamHasMinMax (const char *label, const char *name, TDATA min=0.0, TDATA max=1.0)
void getDisplay (char *text) const
virtual TDATA readout () const
virtual void setReadout (TDATA read)
Public Member Functions inherited from VSTParam
VSTParam ()
VSTParam (const char *label, const char *name)
virtual void setVal (float value)
virtual float getVal (void) const
virtual void getLabel (char *label) const
virtual void getName (char *text) const
Protected Attributes
TDATA min
TDATA max
Protected Attributes inherited from VSTParam
float v
std::string label
std::string name
Detailed Description
template<class TDATA>
class VSTParamHasMinMax< TDATA >
Definition at line 43 of file vst_param.h.
Constructor & Destructor Documentation
template<class TDATA > VSTParamHasMinMax< TDATA >::VSTParamHasMinMax (TDATA min = 0.0, TDATA max = 1.0) inline
Definition at line 50 of file vst_param.h.
 : VSTParam("", ""), min(min), max(max) { }
template<class TDATA > VSTParamHasMinMax< TDATA >::VSTParamHasMinMax (const char * label, const char * name, TDATA min = 0.0, TDATA max = 1.0) inline
Definition at line 51 of file vst_param.h.
 : VSTParam(label, name), min(min), max(max) {}
Member Function Documentation
template<class TDATA > void VSTParamHasMinMax< TDATA >::getDisplay (char * text) const inline virtual
Reimplemented from VSTParam.
Definition at line 53 of file vst_param.h.
References pEffectInstance, and VSTParamHasMinMax< TDATA >::readout().
 { pEffectInstance->float2string((float)readout(), text, kVstMaxParamStrLen); }
template<class TDATA > virtual TDATA VSTParamHasMinMax< TDATA >::readout () const inline virtual
Definition at line 55 of file vst_param.h.
References VSTParamHasMinMax< TDATA >::max, VSTParamHasMinMax< TDATA >::min, and VSTParam::v.
Referenced by VSTParamHasMinMax< TDATA >::getDisplay().
 { return (TDATA)((1.f - v)*min + v*max); }
template<class TDATA > virtual void VSTParamHasMinMax< TDATA >::setReadout (TDATA read) inline virtual
Definition at line 57 of file vst_param.h.
References VSTParamHasMinMax< TDATA >::max, VSTParamHasMinMax< TDATA >::min, and VSTParam::setVal().
 { setVal(((float)read - min)/(max - min)); }
Member Data Documentation
template<class TDATA > TDATA VSTParamHasMinMax< TDATA >::max protected
Definition at line 47 of file vst_param.h.
Referenced by VSTParamHasMinMax< TDATA >::readout(), and VSTParamHasMinMax< TDATA >::setReadout().
template<class TDATA > TDATA VSTParamHasMinMax< TDATA >::min protected
Definition at line 46 of file vst_param.h.
Referenced by VSTParamHasMinMax< TDATA >::readout(), and VSTParamHasMinMax< TDATA >::setReadout().
The documentation for this class was generated from the following file:
vst_param.h