A (Mono)Delay : VST Plug-in Test: RingBuff< TDATA, sz > Class Template Reference
RingBuff< TDATA, sz > Class Template Reference
< TDATA is double or float
#include <ringbuff.h>
Public Member Functions
void decBP (void)
void IncBP (void)
size_t size (void) const
TDATA lerpRead (TDATA adrs) const
TDATA & operator[] (size_t i)
Private Attributes
TDATA buf [sz]
size_t bp
Detailed Description
template<class TDATA, size_t sz>
class RingBuff< TDATA, sz >
< TDATA is double or float
Definition at line 11 of file ringbuff.h.
Member Function Documentation
template<class TDATA, size_t sz> void RingBuff< TDATA, sz >::decBP (void) inline
Definition at line 16 of file ringbuff.h.
Referenced by BFilterIIR1D< TDATA >::process(), BFilterIIR2D< TDATA >::process(), and Fx::processReplacing().
 { bp--; }
template<class TDATA, size_t sz> void RingBuff< TDATA, sz >::IncBP (void) inline
Definition at line 17 of file ringbuff.h.
 { bp++; }
template<class TDATA, size_t sz> TDATA RingBuff< TDATA, sz >::lerpRead (TDATA adrs) const inline
Reading with Linear interpolation
Parameters
adrs read pointer address as floating point
Returns
read data
Definition at line 27 of file ringbuff.h.
         {
                 TDATA intPart;
                 TDATA fracPart = std::modf(adrs, &intPart);
                 size_t iAdrs = static_cast<size_t>(intPart);
                 return (TDATA(1.0)-fracPart)*buf[(bp+iAdrs)%sz] + fracPart*buf[(bp+iAdrs+1)%sz];
         }
template<class TDATA, size_t sz> TDATA& RingBuff< TDATA, sz >::operator[] (size_t i) inline
Definition at line 37 of file ringbuff.h.
 { return buf[(bp+i)%sz]; }
template<class TDATA, size_t sz> size_t RingBuff< TDATA, sz >::size (void) const inline
Definition at line 19 of file ringbuff.h.
 { return sz; }
Member Data Documentation
template<class TDATA, size_t sz> size_t RingBuff< TDATA, sz >::bp private
Definition at line 13 of file ringbuff.h.
Referenced by RingBuff< TDATA, 3 >::decBP(), RingBuff< TDATA, 3 >::IncBP(), RingBuff< TDATA, 3 >::lerpRead(), and RingBuff< TDATA, 3 >::operator[]().
template<class TDATA, size_t sz> TDATA RingBuff< TDATA, sz >::buf[sz] private
Definition at line 12 of file ringbuff.h.
Referenced by RingBuff< TDATA, 3 >::lerpRead(), and RingBuff< TDATA, 3 >::operator[]().
The documentation for this class was generated from the following file:
ringbuff.h