A (Mono)Delay : VST Plug-in Test: FreqSample Class Reference
FreqSample Class Reference
#include <fs.h>
Public Member Functions
FreqSample (float freq=44100.0)
float getFreq () const
float getRate () const
float rate2nsample (float rate)
float freq2nsample (float freq)
Private Attributes
float freq
Detailed Description
Definition at line 11 of file fs.h.
Constructor & Destructor Documentation
FreqSample::FreqSample (float freq = 44100.0) inline
Definition at line 14 of file fs.h.
 : freq(freq) {}
Member Function Documentation
float FreqSample::freq2nsample (float freq) inline
Definition at line 29 of file fs.h.
References freq, and getFreq().
 { return getFreq()/freq; }
float FreqSample::getFreq () const inline
Definition at line 16 of file fs.h.
References freq, and pEffectInstance.
Referenced by BFilterSVF< TDATA >::calcCoef(), freq2nsample(), and Fx::processReplacing().
         {
                 if(pEffectInstance)     return pEffectInstance->getSampleRate();
                 else                    return freq;
         }
float FreqSample::getRate () const inline
Definition at line 22 of file fs.h.
References freq, and pEffectInstance.
Referenced by BFilterIIR1D< TDATA >::calcCoef(), BFilterIIR2D< TDATA >::calcCoef(), and rate2nsample().
         {
                 if(pEffectInstance)     return 1.f/pEffectInstance->getSampleRate();
                 else                    return 1.f/freq;
         }
float FreqSample::rate2nsample (float rate) inline
Definition at line 28 of file fs.h.
References getRate().
 { return rate/getRate(); }
Member Data Documentation
float FreqSample::freq private
Definition at line 12 of file fs.h.
Referenced by freq2nsample(), getFreq(), and getRate().
The documentation for this class was generated from the following file:
fs.h