A (Mono)Delay : VST Plug-in Test: Fx Class Reference
Fx Class Reference
#include <fx.h>
Public Member Functions
Fx (audioMasterCallback audioMaster)
‾Fx ()
void setupParam ()
virtual void processReplacing (float **inputs, float **outputs, VstInt32 sampleFrames)
virtual void setProgramName (char *name)
virtual void getProgramName (char *name)
virtual void setParameter (VstInt32 index, float value)
virtual float getParameter (VstInt32 index)
virtual void getParameterLabel (VstInt32 index, char *label)
virtual void getParameterDisplay (VstInt32 index, char *text)
virtual void getParameterName (VstInt32 index, char *text)
virtual bool getEffectName (char *name)
virtual bool getVendorString (char *text)
virtual bool getProductString (char *text)
virtual VstInt32 getVendorVersion ()
Protected Attributes
char programName [kVstMaxProgNameLen+1]
Private Member Functions
void setSampleRate (float freq)
Detailed Description
Definition at line 24 of file fx.h.
Constructor & Destructor Documentation
Fx::Fx (audioMasterCallback audioMaster)
Definition at line 84 of file fx.cpp.
References programName, setupParam(), and UNIQ_ID.
 : AudioEffectX (audioMaster, 1, kNumParams)
 {
         setNumInputs (2);               // stereo in
         setNumOutputs (2);              // stereo out
         setUniqueID (UNIQ_ID);  // identify
         canProcessReplacing (); // supports replacing output
 //      canDoubleReplacing ();  // supports double precision processing
         vst_strncpy (programName, "Default", kVstMaxProgNameLen);       // default program name
         setupParam();
 }
Member Function Documentation
bool Fx::getEffectName (char * name) virtual
Definition at line 148 of file fx.cpp.
References kEffectName.
 {
         vst_strncpy (name, kEffectName, kVstMaxEffectNameLen);
         return true;
 }
float Fx::getParameter (VstInt32 index) virtual
Definition at line 124 of file fx.cpp.
References VSTParam::getVal(), and param.
 {
         return param[index]->getVal();
 }
void Fx::getParameterDisplay (VstInt32 index, char * text) virtual
Definition at line 136 of file fx.cpp.
References VSTParam::getDisplay(), and param.
 {
         param[index]->getDisplay (text);
 }
void Fx::getParameterLabel (VstInt32 index, char * label) virtual
Definition at line 142 of file fx.cpp.
References VSTParam::getLabel(), and param.
 {
         param[index]->getLabel(label);
 }
void Fx::getParameterName (VstInt32 index, char * text) virtual
Definition at line 130 of file fx.cpp.
References VSTParam::getName(), and param.
 {
         param[index]->getName(label);
 }
bool Fx::getProductString (char * text) virtual
Definition at line 155 of file fx.cpp.
References kProductString.
 {
         vst_strncpy (text, kProductString, kVstMaxProductStrLen);
         return true;
 }
void Fx::getProgramName (char * name) virtual
Definition at line 112 of file fx.cpp.
References programName.
 {
         vst_strncpy (name, programName, kVstMaxProgNameLen);
 }
bool Fx::getVendorString (char * text) virtual
Definition at line 162 of file fx.cpp.
References kVendorString.
 {
         vst_strncpy (text, kVendorString, kVstMaxVendorStrLen);
         return true;
 }
VstInt32 Fx::getVendorVersion () virtual
Definition at line 169 of file fx.cpp.
 {
         return 1000;
 }
void Fx::processReplacing (float ** inputs, float ** outputs, VstInt32 sampleFrames) virtual
Definition at line 47 of file fx.cpp.
References dcCut, RingBuff< TDATA, sz >::decBP(), delayFeedback, delayTime, delayWet, Fs, FreqSample::getFreq(), and VSTParam::getVal().
 {
     float* in1  =  inputs[0];
     float* in2  =  inputs[1];
     float* out1 = outputs[0];
     float* out2 = outputs[1];
     while (--sampleFrames >= 0)
     {
         float dryLch = (*in1++);
         float dryRch = (*in2++);
         delayBuf.decBP();
         // Calc Read Pointer Address
         size_t rAdrs = (size_t)(Fs.getFreq()*delayTime.getVal());
         if(rAdrs <= 0)  rAdrs = 1;
         float wet = delayBuf[rAdrs];
         delayBuf[0] = (dryLch + dryRch)/2.f + dcCut.process(delayFeedback.getVal() * wet);
         wet *= delayWet.getVal();
         (*out1++) = dryLch + +wet;
         (*out2++) = dryLch + +wet;
     }
 }
void Fx::setParameter (VstInt32 index, float value) virtual
Definition at line 118 of file fx.cpp.
References param, and VSTParam::setVal().
 {
         param[index]->setVal(value);
 }
void Fx::setProgramName (char * name) virtual
Definition at line 106 of file fx.cpp.
References programName.
 {
         vst_strncpy (programName, name, kVstMaxProgNameLen);
 }
void Fx::setSampleRate (float freq) private
Definition at line 40 of file fx.cpp.
References dcCut.
 {
         dcCut.setSampleFreq(freq);
 }
void Fx::setupParam ()
Definition at line 32 of file param.cpp.
References delayFeedback, delayTime, delayWet, and VSTParam::setVal().
Referenced by Fx().
 {
         delayTime.setVal(0.34f);
         delayFeedback.setVal(0.3f);
         delayWet.setVal(0.5);
 }
Fx::‾Fx ()
Definition at line 99 of file fx.cpp.
 {
         // nothing to do here
 }
Member Data Documentation
char Fx::programName[kVstMaxProgNameLen+1] protected
Definition at line 54 of file fx.h.
Referenced by Fx(), getProgramName(), and setProgramName().
The documentation for this class was generated from the following files:
fx.h
fx.cpp
param.cpp