A (Mono)Delay : VST Plug-in Test: BFilterIIR2D< TDATA > Class Template Reference
BFilterIIR2D< TDATA > Class Template Reference
#include <bfilter.h>
Public Member Functions
BFilterIIR2D (PassType pt=kPassTypeLPF, float f=1000.0, float q=0.707)
TDATA process (TDATA in)
void setQ (float q)
float getQ () const
Public Member Functions inherited from BFilter
BFilter (PassType pt=kPassTypeLPF, float f=1000.0)
void setSampleFreq (float freq)
virtual void setPassType (PassType type)
virtual void setFreq (float freq)
PassType getPassType () const
float getFreq () const
Private Member Functions
void calcCoef ()
Private Attributes
RingBuff< TDATA, 3 > buf
float Q
float coef [5]
Additional Inherited Members
Public Types inherited from BFilter
enum PassType {
kPassTypeLPF = 0, kPassTypeBPF, kPassTypeHPF, kPassTypeAPF,
kNumOfPassType
}
Protected Member Functions inherited from BFilter
float freq2wc (float f)
Protected Attributes inherited from BFilter
float freq
PassType passType
Detailed Description
template<class TDATA>
class BFilterIIR2D< TDATA >
Definition at line 112 of file bfilter.h.
Constructor & Destructor Documentation
template<class TDATA > BFilterIIR2D< TDATA >::BFilterIIR2D (PassType pt = kPassTypeLPF, float f = 1000.0, float q = 0.707) inline
Definition at line 158 of file bfilter.h.
References BFilterIIR2D< TDATA >::calcCoef().
 : BFilter(pt, f), Q(q) { calcCoef(); }
Member Function Documentation
template<class TDATA > void BFilterIIR2D< TDATA >::calcCoef () inline private virtual
Reimplemented from BFilter.
Definition at line 118 of file bfilter.h.
References BFilterIIR2D< TDATA >::coef, BFilter::freq, BFilter::freq2wc(), Fs, FreqSample::getRate(), BFilter::kPassTypeAPF, BFilter::kPassTypeBPF, BFilter::kPassTypeHPF, BFilter::kPassTypeLPF, BFilter::passType, BFilterIIR2D< TDATA >::Q, s2z(), and s2zPrewarping().
Referenced by BFilterIIR2D< TDATA >::BFilterIIR2D(), and BFilterIIR2D< TDATA >::setQ().
         {
                 if(freq <= 0.0) return;
                 if(Q <= 0.0)    return;
                 float wc = s2zPrewarping(freq2wc(freq), Fs.getRate());
                 float a[3], b[3];
                 float c[3], d[3];
                 switch(passType) {
                 case kPassTypeAPF:
                         a[0] = wc*wc;   a[1] = -wc/Q;   a[2] = 1.0;
                         b[0] = wc*wc;   b[1] = wc/Q;    b[2] = 1.0;
                         break;
                 case kPassTypeHPF:
                         a[0] = 0.0;     a[1] = 0.0;     a[2] = 1.0;
                         b[0] = wc*wc;   b[1] = wc/Q;    b[2] = 1.0;
                         break;
                 case kPassTypeBPF:
                         a[0] = 0.0;     a[1] = wc/Q;    a[2] = 0.0;
                         b[0] = wc*wc;   b[1] = wc/Q;    b[2] = 1.0;
                         break;
                 case kPassTypeLPF:
                 default:
                         a[0] = wc*wc;   a[1] = 0.0;     a[2] = 0.0;
                         b[0] = wc*wc;   b[1] = wc/Q;    b[2] = 1.0;
                         break;
                 }
                 s2z(a, b, c, d, 2, Fs.getRate());
                 coef[0] = c[0];
                 coef[1] = c[1];
                 coef[2] = c[2];
                 coef[3] = -1.f*d[1];
                 coef[4] = -1.f*d[2];
         }
template<class TDATA > float BFilterIIR2D< TDATA >::getQ () const inline
Definition at line 176 of file bfilter.h.
References BFilterIIR2D< TDATA >::Q.
 { return Q; }
template<class TDATA > TDATA BFilterIIR2D< TDATA >::process (TDATA in) inline
Definition at line 160 of file bfilter.h.
References BFilterIIR2D< TDATA >::buf, BFilterIIR2D< TDATA >::coef, and RingBuff< TDATA, sz >::decBP().
         {
                 buf.decBP();
                 TDATA
                 acc  = coef[3] * buf[1] + in;
                 acc += coef[4] * buf[2];
                 acc  = coef[0] * (buf[0] = acc);
                 acc += coef[1] * buf[1];
                 acc += coef[2] * buf[2];
                 return acc;
         }
template<class TDATA > void BFilterIIR2D< TDATA >::setQ (float q) inline
Definition at line 175 of file bfilter.h.
References BFilterIIR2D< TDATA >::calcCoef(), and BFilterIIR2D< TDATA >::Q.
 { Q = q; calcCoef(); }
Member Data Documentation
template<class TDATA > RingBuff<TDATA, 3> BFilterIIR2D< TDATA >::buf private
Definition at line 114 of file bfilter.h.
Referenced by BFilterIIR2D< TDATA >::process().
template<class TDATA > float BFilterIIR2D< TDATA >::coef[5] private
Definition at line 116 of file bfilter.h.
Referenced by BFilterIIR2D< TDATA >::calcCoef(), and BFilterIIR2D< TDATA >::process().
template<class TDATA > float BFilterIIR2D< TDATA >::Q private
Definition at line 115 of file bfilter.h.
Referenced by BFilterIIR2D< TDATA >::calcCoef(), BFilterIIR2D< TDATA >::getQ(), and BFilterIIR2D< TDATA >::setQ().
The documentation for this class was generated from the following file:
bfilter.h