A (Mono)Delay : VST Plug-in Test: VSTParam Class Reference
VSTParam Class Reference
< for pEffectInstance
#include <vst_param.h>
Public Member Functions
VSTParam ()
VSTParam (const char *label, const char *name)
virtual void setVal (float value)
virtual float getVal (void) const
virtual void getLabel (char *label) const
virtual void getName (char *text) const
virtual void getDisplay (char *text) const
Protected Attributes
float v
std::string label
std::string name
Detailed Description
< for pEffectInstance
Definition at line 19 of file vst_param.h.
Constructor & Destructor Documentation
VSTParam::VSTParam () inline
Definition at line 25 of file vst_param.h.
 {}
VSTParam::VSTParam (const char * label, const char * name) inline
Definition at line 26 of file vst_param.h.
 : label(label), name(name) { }
Member Function Documentation
virtual void VSTParam::getDisplay (char * text) const inline virtual
Reimplemented in VSTParamHasMinMax< TDATA >.
Definition at line 35 of file vst_param.h.
References pEffectInstance, and v.
Referenced by Fx::getParameterDisplay().
 { pEffectInstance->float2string(v, text, kVstMaxParamStrLen); }
virtual void VSTParam::getLabel (char * label) const inline virtual
Definition at line 32 of file vst_param.h.
Referenced by Fx::getParameterLabel().
 { vst_strncpy(label, this->label.c_str(), kVstMaxParamStrLen); }
virtual void VSTParam::getName (char * text) const inline virtual
Definition at line 33 of file vst_param.h.
References name.
Referenced by Fx::getParameterName().
 { vst_strncpy(text, this->name.c_str(), kVstMaxParamStrLen); }
virtual float VSTParam::getVal (void) const inline virtual
Definition at line 29 of file vst_param.h.
References v.
Referenced by Fx::getParameter(), and Fx::processReplacing().
 { return v; }
virtual void VSTParam::setVal (float value) inline virtual
Definition at line 28 of file vst_param.h.
References v.
Referenced by Fx::setParameter(), VSTParamHasMinMax< TDATA >::setReadout(), and Fx::setupParam().
 { v = value; }
Member Data Documentation
std::string VSTParam::label protected
Definition at line 22 of file vst_param.h.
std::string VSTParam::name protected
Definition at line 23 of file vst_param.h.
Referenced by getName().
float VSTParam::v protected
Definition at line 21 of file vst_param.h.
Referenced by getDisplay(), getVal(), VSTParamHasMinMax< TDATA >::readout(), and setVal().
The documentation for this class was generated from the following file:
vst_param.h