A (Mono)Delay : VST Plug-in Test: BFilterIIR1D< TDATA > Class Template Reference
BFilterIIR1D< TDATA > Class Template Reference
#include <bfilter.h>
Public Member Functions
BFilterIIR1D (PassType pt=kPassTypeLPF, float f=1000.0)
TDATA process (TDATA in)
Public Member Functions inherited from BFilter
BFilter (PassType pt=kPassTypeLPF, float f=1000.0)
void setSampleFreq (float freq)
virtual void setPassType (PassType type)
virtual void setFreq (float freq)
PassType getPassType () const
float getFreq () const
Private Member Functions
void calcCoef ()
Private Attributes
RingBuff< TDATA, 2 > buf
float coef [3]
Additional Inherited Members
Public Types inherited from BFilter
enum PassType {
kPassTypeLPF = 0, kPassTypeBPF, kPassTypeHPF, kPassTypeAPF,
kNumOfPassType
}
Protected Member Functions inherited from BFilter
float freq2wc (float f)
Protected Attributes inherited from BFilter
float freq
PassType passType
Detailed Description
template<class TDATA>
class BFilterIIR1D< TDATA >
Definition at line 55 of file bfilter.h.
Constructor & Destructor Documentation
template<class TDATA> BFilterIIR1D< TDATA >::BFilterIIR1D (PassType pt = kPassTypeLPF, float f = 1000.0) inline
Definition at line 92 of file bfilter.h.
References BFilterIIR1D< TDATA >::calcCoef().
 : BFilter(pt, f) { calcCoef(); }
Member Function Documentation
template<class TDATA> void BFilterIIR1D< TDATA >::calcCoef () inline private virtual
Reimplemented from BFilter.
Definition at line 59 of file bfilter.h.
References BFilterIIR1D< TDATA >::coef, BFilter::freq, BFilter::freq2wc(), Fs, FreqSample::getRate(), BFilter::kPassTypeAPF, BFilter::kPassTypeHPF, BFilter::kPassTypeLPF, BFilter::passType, s2z(), and s2zPrewarping().
Referenced by BFilterIIR1D< TDATA >::BFilterIIR1D().
         {
                 if(freq <= 0.0) return;
                 float wc = s2zPrewarping(freq2wc(freq), Fs.getRate());
                 float a[2], b[2];
                 float c[2], d[2];
                 switch(passType) {
                 case kPassTypeAPF:
                         a[0] = wc; a[1] = -1.0;
                         b[0] = wc; b[1] = 1.0;
                         break;
                 case kPassTypeHPF:
                         a[0] = 0.0; a[1] = 1.0;
                         b[0] = wc;b[1] = 1.0;
                         break;
                 case kPassTypeLPF:
                 default:
                         a[0] = wc; a[1] = 0.0;
                         b[0] = wc; b[1] = 1.0;
                         break;
                 }
                 s2z(a, b, c, d, 1, Fs.getRate());
                 coef[0] = c[0];
                 coef[1] = c[1];
                 coef[2] = -1.f*d[1];
         }
template<class TDATA> TDATA BFilterIIR1D< TDATA >::process (TDATA in) inline
Definition at line 94 of file bfilter.h.
References BFilterIIR1D< TDATA >::buf, BFilterIIR1D< TDATA >::coef, and RingBuff< TDATA, sz >::decBP().
         {
                 buf.decBP();
                 TDATA
                 acc  = coef[2] * buf[1] + in;
                 acc  = coef[0] * (buf[0] = acc);
                 acc += coef[1] * buf[1];
                 return acc;
         }
Member Data Documentation
template<class TDATA> RingBuff<TDATA, 2> BFilterIIR1D< TDATA >::buf private
Definition at line 57 of file bfilter.h.
Referenced by BFilterIIR1D< TDATA >::process().
template<class TDATA> float BFilterIIR1D< TDATA >::coef[3] private
Definition at line 58 of file bfilter.h.
Referenced by BFilterIIR1D< TDATA >::calcCoef(), and BFilterIIR1D< TDATA >::process().
The documentation for this class was generated from the following file:
bfilter.h