A (Mono)Delay : VST Plug-in Test: BFilter Class Reference
BFilter Class Reference
#include <bfilter.h>
Public Types
enum PassType {
kPassTypeLPF = 0, kPassTypeBPF, kPassTypeHPF, kPassTypeAPF,
kNumOfPassType
}
Public Member Functions
BFilter (PassType pt=kPassTypeLPF, float f=1000.0)
void setSampleFreq (float freq)
virtual void setPassType (PassType type)
virtual void setFreq (float freq)
PassType getPassType () const
float getFreq () const
Protected Member Functions
float freq2wc (float f)
Protected Attributes
float freq
PassType passType
Private Member Functions
virtual void calcCoef ()
Detailed Description
Definition at line 21 of file bfilter.h.
Member Enumeration Documentation
enum BFilter::PassType
Enumerator
kPassTypeLPF
kPassTypeBPF
kPassTypeHPF
kPassTypeAPF
kNumOfPassType
Definition at line 24 of file bfilter.h.
                      {
                 kPassTypeLPF = 0,
                 kPassTypeBPF,
                 kPassTypeHPF,
                 kPassTypeAPF,
                 kNumOfPassType,
         } PassType;
Constructor & Destructor Documentation
BFilter::BFilter (PassType pt = kPassTypeLPF, float f = 1000.0) inline
Definition at line 38 of file bfilter.h.
References calcCoef().
 : passType(pt), freq(f)  { calcCoef(); }
Member Function Documentation
virtual void BFilter::calcCoef () inline private virtual
Reimplemented in BFilterSVF< TDATA >, BFilterIIR2D< TDATA >, and BFilterIIR1D< TDATA >.
Definition at line 32 of file bfilter.h.
Referenced by BFilter(), setFreq(), setPassType(), and setSampleFreq().
 { };
float BFilter::freq2wc (float f) inline protected
Definition at line 36 of file bfilter.h.
References M_PI.
Referenced by BFilterIIR1D< TDATA >::calcCoef(), and BFilterIIR2D< TDATA >::calcCoef().
 { return float(2.0*M_PI)*f; }
float BFilter::getFreq () const inline
Definition at line 46 of file bfilter.h.
References freq.
 { return freq; }
PassType BFilter::getPassType () const inline
Definition at line 45 of file bfilter.h.
References passType.
 { return passType; }
virtual void BFilter::setFreq (float freq) inline virtual
Definition at line 43 of file bfilter.h.
References calcCoef(), and freq.
 { this->freq = freq; calcCoef(); }
virtual void BFilter::setPassType (PassType type) inline virtual
Definition at line 42 of file bfilter.h.
References calcCoef(), and passType.
 { passType = type; calcCoef(); }
void BFilter::setSampleFreq (float freq) inline
Definition at line 40 of file bfilter.h.
References calcCoef().
 { calcCoef(); }
Member Data Documentation
float BFilter::freq protected
Definition at line 32 of file bfilter.h.
Referenced by BFilterIIR1D< TDATA >::calcCoef(), BFilterIIR2D< TDATA >::calcCoef(), BFilterSVF< TDATA >::calcCoef(), getFreq(), and setFreq().
PassType BFilter::passType protected
Definition at line 35 of file bfilter.h.
Referenced by BFilterIIR1D< TDATA >::calcCoef(), BFilterIIR2D< TDATA >::calcCoef(), BFilterSVF< TDATA >::calcCoef(), getPassType(), and setPassType().
The documentation for this class was generated from the following file:
bfilter.h