A (Mono)Delay : VST Plug-in Test: s2z.h File Reference
s2z.h File Reference
Macros
#define S2Z_TYPE float
Functions
void s2z (const S2Z_TYPE *a, const S2Z_TYPE *b, S2Z_TYPE *c, S2Z_TYPE *d, int N, S2Z_TYPE T)
S2Z_TYPE s2zPrewarping (S2Z_TYPE wa, S2Z_TYPE T)
Macro Definition Documentation
#define S2Z_TYPE float
Definition at line 11 of file s2z.h.
Referenced by s2zPrewarping().
Function Documentation
void s2z (const S2Z_TYPE * a, const S2Z_TYPE * b, S2Z_TYPE * c, S2Z_TYPE * d, int N, S2Z_TYPE T)
Definition at line 26 of file s2z.c.
Referenced by BFilterIIR1D< TDATA >::calcCoef(), and BFilterIIR2D< TDATA >::calcCoef().
 {
         int n;
         for(n = N; (0.0 == a[n]) && (0.0 == b[n]) && (1 < n); n--) {
                 c[n] = 0.0;
                 d[n] = 0.0;
         }
         a2c(a, c, n, T);
         a2c(b, d, n, T);
         Normalize(c, d, n);
 }
S2Z_TYPE s2zPrewarping (S2Z_TYPE wa, S2Z_TYPE T)
Definition at line 92 of file s2z.c.
References S2Z_TYPE.
Referenced by BFilterIIR1D< TDATA >::calcCoef(), and BFilterIIR2D< TDATA >::calcCoef().
 {
         return  (S2Z_TYPE)(2.0*tan(wa*T/2.0)/T);
 }